name: Notify on New Issue

on:
  issues:
    types: [opened]

jobs:
  run_python:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: filter issue with rule
        uses: ElyssaJyu/Auto-Digest
        run: |
          python Filter_Rule.py
