name: "get issue summary of yesterday"
description: "This action will make a daily issue summary"
author: "shangminx"

branding:
  icon: "book-open"
  color: "green"

outputs:
  dailysummary:
    description: "the daily summary of issues"
    value: ${{ steps.pythonscript.outputs.dailysummary }}
    
runs:
  using: "composite"
  steps:
  - name: Check out repository code
    uses: actions/checkout@v3
    with:
      repository: Shangminx/Auto-Digest
  - name: Set up Python
    uses: actions/setup-python@v2
    with:
      python-version: '3.x'
  - name: Install dependencies 
    shell: bash
    run: | 
      python -m pip install --upgrade pip 
      pip install requests
  - name: Run python script
    id: pythonscript
    shell: bash
    run: | 
      rawoutput=$(python .github/workflows/main.py)
      output=${rawoutput/\'/"\'"}
      output=${output/\"/"\\\""}
      echo "::set-output name=dailysummary::$output"
  - name: check python script
    shell: bash
    run: |
      echo "${{ steps.pythonscript.outputs.dailysummary }}"

