name: "get issue summary of yesterday"
description: "This action will make a daily issue summary"
author: "shangminx"

branding:
  icon: "book-open"
  color: "green"

inputs:
  daily_or_weekly:
    description: "0 means daily summary 1 means weekly summary"
    require: true

outputs:
  dailysummary:
    description: "the daily summary of issues"
    value: ${{ steps.pythonscript.outputs.dailysummary }}
    
runs:
  using: "composite"
  steps:
  - name: Check out repository code
    uses: actions/checkout@v3
    with:
      repository: Shangminx/Auto-Digest
  - name: Set up Python
    uses: actions/setup-python@v2
    with:
      python-version: '3.x'
  - name: Install dependencies 
    shell: bash
    run: | 
      python -m pip install --upgrade pip 
      pip install requests
  - name: Run python script
    id: pythonscript
    shell: bash
    run: | 
      output=$(python .github/workflows/main.py ${{ inputs.daily_or_weekly }})
      outputstr=${output//'/\'}
      echo "::set-output name=dailysummary::$output"
      echo "$outputstr"
