name: get security issue by title and body

on:
  issues:
    types: [opened]

jobs:
  alert:
    runs-on: ubuntu-latest
    name: get security issue by title and body
    steps: 
    - uses: xu-ms/github-actions-issue-to-open@simple-sync
      id: script
      env:
        title: "${{ github.event.issue.title }}"
        body: "${{ github.event.issue.body }}"
        created_at: "${{ github.event.issue.created_at }}"
        number: "${{ github.event.issue.number }}"
        html_url: "${{ github.event.issue.html_url }}"
    - run: |
        jsonData="${{ needs.script.outputs.json-data }}"
        echo "$jsonData"
