name: get security issue by title and body

on:
  issues:
    types: [opened]

jobs:
  alert:
    runs-on: ubuntu-latest
    name: get security issue by title and body
    steps: 
    - name: filter issue by keyword
      id: script
      uses: xu-ms/github-actions-issue-to-open@simple-sync
    - name: need send and get issue info
      if: ${{ steps.script.outputs.need_attention == 'true'}}
      run: |
        echo "ready to send email"
    - name: do not need send
      if: ${{ steps.script.outputs.need_attention == 'false'}}
      run: echo "${{ github.event.issue.html_url }}"
