name: get issue summary of yesterday

on:
  workflow_dispatch:
  schedule:
    - cron:  '0/1 * * * *'
  
jobs:
  alert:
    runs-on: ubuntu-latest
    name: get summary
    steps:
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies 
      shell: bash
      run: | 
        python -m pip install --upgrade pip 
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run ls
      shell: bash
      run: | 
        ls -la
    - name: Run python script 
      shell: bash
      run: | 
        cd ${{ github.workspace }}
        python main.py
